#!/usr/bin/env bash

# This command will remove any local branches that have been merged into dev.

if [ "$1" == "merged" ]; then
branches=`git branch -a --merged | grep -v "master" | cut -d'/' -f3`

for branch in $branches; do
    echo $branch
    $(git branch -D $branch 2> /dev/null)
done

elif [ "$1" == "local" ]; then
    # the following command gets rid of local remote/* branches
    # that are no longer on GitHub.
    git fetch origin --prune
fi
